### ISSUE TITLE
go build fail

### ISSUE THREAD

**Issue by xiangfengsu** [rendora/rendora#2]
`➜  rendora git:(master) go build
go: golang.org/x/text@v0.3.0: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20181107165924-66b7b1311ac8: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20180906133057-8cf3aee42992: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20181031143558-9b800f95dbbc: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: error loading module requirements`

These resource addresses are 404

**Comment by geokb** [comment]
What is your golang version? Rendora needs 1.11 because it uses go modules

**Comment by xiangfengsu** [comment]
Sorry, it's my proxy’s problem. problem solved, thank you

**Comment by wolfjobs** [comment]
`go version`
`go version go1.12.6 linux/386`
but i got the same problem
