### ISSUE TITLE
Rendora cannot even render a "Hello-World" React Project

### ISSUE THREAD

**Issue by po-trottier** [rendora/rendora#25]
After following this tutorial:
https://hashnode.com/post/instantly-solving-seo-and-providing-ssr-for-modern-javascript-websites-independently-of-frontend-and-backend-stacks-cjpuy274b01br3zs1zr46awfz

I realised that Rendora seemed broken. No matter what I do, I cannot seem to connect to the port listened-to by Rendora, and therefore cannot get any SSR-ed content.

My Config:

listen:
    port: 3001

backend:
    url: http://127.0.0.1:3000

target:
    url: http://127.0.0.1

filters:
    userAgent:
        defaultPolicy: whitelist

Example Project:
https://github.com/po-trottier/rendora-test
To run the project, start 2 terminal, in the first one write "npm start" in the second one write "docker-compose up". You will need docker-desktop and node installed.

Important Note:
I also tried to run it with a VueJS Project running on NGINX and got the same result.

**Comment by u8983478934** [comment]
It is not broken, I use it in production so are many others, it's just you who are too lazy to get even a "Hello World" project right. Even though your config seem incomplete but it most probably you didn't put Rendora as your upstream in nginx and kept the backend connected directly.

**Comment by geokb** [comment]
I apologize but your issue is totally misleading to say the least. Please give me more details about your problem so I can tell what's wrong with your setup.

**Comment by po-trottier** [comment]
Hi,

Sorry for the confusion, I am by no means an Expert in the matter. The GitHub project linked in the original post is a good example of a setup that I didn't manage to get to work.

As for the actual project I am attempting to use Rendora for, here is my NGINX config:

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        off;

    keepalive_timeout  60;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}


And here is my Docker-Compose config:

version: '3'
services:
    headless:
        image: rendora/chrome-headless:latest
        ports:
            - "9222:9222"
        tmpfs:
            - /tmp
    nginx:
        image: MyImage
        ports:
            - "4000:80"
    rendora:
        image: rendora/rendora
        network_mode: "host"
        volumes:
            - /rendora:/etc/rendora

Thanks for your help!

**Comment by po-trottier** [comment]
@geokb In case also help you to see the Dockerfile config ?

# Create the container from the bitbucket image
FROM atlassian/default-image:2 as build-stage
# Create the directories we will need
RUN mkdir -p /PROJECT
# Set the directory we want to run the next commands for
WORKDIR /PROJECT
# Copy our source code into the container
COPY package*.json ./
# Install the dependencies
RUN npm install
# Copy dependencies to docker
COPY . .
# Run webpack and the vue-loader
RUN npm run build

# Setup the NGINX container
FROM nginx:stable-alpine as production-stage
# Create the directories we will need
RUN mkdir -p /var/log/nginx
RUN mkdir -p /var/www/html
# Copy the respective nginx configuration files
COPY nginx_config/nginx.conf /etc/nginx/nginx.conf
COPY nginx_config/default.conf /etc/nginx/conf.d/default.conf
# Copy the built app to our served directory
COPY --from=build-stage /PROJECT/dist /var/www/html
# Make all files belong to the nginx user
RUN chown nginx:nginx /var/www/html
# Expose the port being served
EXPOSE 80
# Start nginx and keep the process from backgrounding and the container from quitting
CMD ["nginx", "-g", "daemon off;"]

**_Note: Most of these configs have been taken directly from the VueJS Documentation Tutorials._**
