### ISSUE TITLE
rendora does not take effect

### ISSUE THREAD

**Issue by Fullsize** [rendora/rendora#32]
![image](https://user-images.githubusercontent.com/30223113/72232201-85234a00-35fa-11ea-8701-eb68bddcb13d.png)
Page blank
seo is not updated

config
![image](https://user-images.githubusercontent.com/30223113/72232251-d29fb700-35fa-11ea-805d-22dbcc2e7999.png)

docker config
![image](https://user-images.githubusercontent.com/30223113/72232262-e4815a00-35fa-11ea-81c1-1058a358c4a2.png)

**Comment by Sparks-Lu** [comment]
Same issue happens.
Could you share how to solve it?
Thanks in advance.
@Fullsize
