### ISSUE TITLE
invalid URL

### ISSUE THREAD

**Issue by xiangfengsu** [rendora/rendora#7]
run ./rendora --config config.yml 

Get http://::1:9222/json/new: invalid URL port ":1:9222"

**Comment by geokb** [comment]
This actually has nothing to do with rendora or golang, you must enclose ipv6 hostnames with square brackets when explicitly using ports in the urls, so you must replace `http://::1:9222`with `http://[::1]:9222`in the config file, here is the rule in rfc3986

> A host identified by an Internet Protocol literal address, version 6 [RFC3513] or later, is distinguished by enclosing the IP literal within square brackets ("[" and "]"). This is the only place where square bracket characters are allowed in the URI syntax. In anticipation of future, as-yet-undefined IP literal address formats, an implementation may use an optional version flag to indicate such a format explicitly rather than rely on heuristic determination

https://tools.ietf.org/html/rfc3986#section-3.3
